<div id='panel'>
    <p><a href="/admin/edition/create"><?php print $this->translate("#New Book") ?></a> |
    <a href="/admin/index/list-works"><?php print $this->translate("#List works") ?></a></p>
    <p><a href="/admin/post/create"><?php print $this->translate("#New Post") ?></a> |
    <a href="/admin/index/list-posts"><?php print $this->translate("#List posts") ?></a></p>
    <a href="/auth/logout"><?php print $this->translate("#Logout") ?></a>
</div>

