<div class='panel'>
    <p><a href="/admin/edition/create"><?php print $this->translate("#New Book") ?></a> |
    <a href="/admin/index/list-works"><?php print $this->translate("#List works") ?></a> |...| 
    <a href="/admin/post/create"><?php print $this->translate("#New Post") ?></a> |
    <a href="/admin/index/list-posts"><?php print $this->translate("#List posts") ?></a> |...|
    <a href="/admin/question/create"><?php print $this->translate("#New Question") ?></a> |
    <a href="/admin/index/list-questions"><?php print $this->translate("#List questions") ?></a> |...|
    <a href="/auth/logout"><?php print $this->translate("#Logout") ?></a></p>
</div>

