<?php
$pageData = $this->pageData;
$faqData = $pageData['faqData'];

?>
<!-- conteudo -->
<div id="conteudo">

<h1><img id="top" src="/img/icone_faq.png" align="absmiddle" alt="<?php echo $this->translate("#Frequently asked questions") ?>" /> <?php echo $this->translate("#Frequently asked questions") ?></h1>

<form id="callQuestionAndAnswer" >
<select id="questionToShow" >
<option <?php echo ($this->questionSelected ? 'selected="selected"' : '') ?>><?php echo $this->translate("#(the answer you are looking may be here)") ?></option>
<?php
$this->faqsLoopSelect($faqData);
?>
</select>


</form>
<?php
$this->faqsLoop($faqData);
?>

<div id="questionAndAnswer"></div>


</div>
<!-- /conteudo -->
        <script type="text/javascript">

        $(document).ready(function(){


            $('#questionToShow').change(function(){
                var current = $(this).val();

                window.location = '#question-' + current;

            });

        });

        </script>
