<?php
$pageData = $this->pageData;
?>
<!-- conteudo -->
<div id="conteudo">

<h1><img src="/img/icone_novidades.png" align="absmiddle" alt="<?php echo $this->translate("#Blog title") ?>" /> <?php echo $this->translate("#Blog title") ?></h1>


<h3><?php echo $pageData['title'] ?></h3>
<p><?php echo $pageData['publicationDate'] ?> | <?php echo $this->categoryHrefTerm($pageData['categoryModel']) ?><!-- | <a href="" title=""><img src="/img/icone_comentario.png" align="absmiddle" /> <strong>Comente</strong></a>--></p>
<div id="explore"><?php echo $pageData['content'] ?></div>
<!-- tags -->
<!--<p>Tags: <a href="" class="tag_2">encontro-literario</a>, <a href="" class="tag_2">palestra</a>, <a href="" class="tag_2">livros</a>, <a href="" class="tag_2">escola</a>, <a href="" class="tag_2">luva</a>, <a href="" class="tag_2">infamia</a></p>-->
<!-- /tags -->

</div>

<!-- /conteudo -->
<script>
$(document).ready(function() {

    var cc = 1;

	// this converts images in the bodycopy to have captions under them
	$("#explore img[alt]").each(function() {
    		var $img = $(this);
		var width = $img.width();
                var divWidth = $img.width() + 40;
		var imgClass = $img.attr('class');
		var imgStyle = $img.attr('style');
		var $div = $("<div />")
			.attr('class', 'img_legenda ' + imgClass)
			.attr('style', imgStyle)
			.css('width', divWidth + 'px');
		$img.wrap($div).removeClass(imgClass).removeAttr('style').attr('width', width  + 'px');
		$('<p class="legenda">' + $img.attr('alt') + '</p>').insertAfter($img);
	});

});
    </script>