<?php
$pageData = $this->pageData;
?>
<!-- conteudo -->
<div id="conteudo">

<h1><img src="/img/icone_novidades.png" align="absmiddle" alt="<?php echo $this->translate("#Blog title") ?>" /> <?php echo $this->translate("#Blog title") ?></h1>


<h3><?php echo $pageData['title'] ?></h3>
<p><?php echo $pageData['publicationDate'] ?> | <a href="" title=""><strong>Leitura</strong></a> | <a href="" title=""><img src="/img/icone_comentario.png" align="absmiddle" /> <strong>Comente</strong></a></p>
<div class="xpto"><?php echo $pageData['content'] ?></div>
<!-- tags -->
<p>Tags: <a href="" class="tag_2">encontro-literario</a>, <a href="" class="tag_2">palestra</a>, <a href="" class="tag_2">livros</a>, <a href="" class="tag_2">escola</a>, <a href="" class="tag_2">luva</a>, <a href="" class="tag_2">infamia</a></p>
<!-- /tags -->

<!-- compartilhamento -->
<div class="box_conteudo"><strong>Compartilhe:</strong></div>
<!-- /compartilhamento -->

<!-- comentarios -->
<div class="box_conteudo clearfix">
<h4 class="comentario">Coment&aacute;rios</h4>

<!-- item de repeticao -->
<div class="item_comentario">
<p><strong>Fabiana Lizak</strong> disse:</p>
<p><small>28.08.2011 &agrave;s 10:51</small></p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi viverra, nunc sed bibendum consequat, lacus erat volutpat sem, et pellentesque urna lacus id metus. Integer fermentum urna eu lectus fringilla rhoncus. Morbi eget mauris augue integer nec.</p>
</div>
<!-- /item de repeticao -->

<!-- item de repeticao -->
<div class="item_comentario">
<p><strong>Fabiana Lizak</strong> disse:</p>
<p><small>28.08.2011 &agrave;s 10:51</small></p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi viverra, nunc sed bibendum consequat, lacus erat volutpat sem, et pellentesque urna lacus id metus. Integer fermentum urna eu lectus fringilla rhoncus. Morbi eget mauris augue integer nec.</p>
</div>
<!-- /item de repeticao -->

</div>
<!-- /comentarios -->

<!-- comente -->
<div class="box_conteudo clearfix" style="padding-bottom:20px;">
<h4 class="comentario">Comente</h4>
<form>
<textarea rows="8" class="comentario">Escreva o seu coment&aacute;rio aqui.</textarea>
<p>Preencha os seus dados abaixo ou clique em um &iacute;cone para login: <a href=""><img align="absmiddle" src="/img/icone_comentario_wp.png" /></a> <a href=""><img align="absmiddle" src="/img/icone_comentario_twitter.png" /></a> <a href=""><img align="absmiddle" src="/img/icone_comentario_facebook.png" /></a></p>
<input type="text" class="comentario" value="E-mail (obrigat&oacute;rio)" />
<input type="text" class="comentario" value="Nome (obrigat&oacute;rio)" />
<input type="text" class="comentario" value="Website" />
<input type="checkbox" /> Quero ser notificado de coment&aacute;rios adicionais por email.<br /><br />
<input type="checkbox" /> Quero ser notificado de novos posts por email.<br /><br />
<input type="submit" value="Enviar coment&aacute;rio" />
</form>
</div>
<!-- /comente -->

</div>

<!-- /conteudo -->