<script type="text/javascript">
    $(document).ready(function(){

            $('#page_container').pajinate({
					num_page_links_to_display : 13,
					items_per_page : 10,
                                        nav_label_first: '<?php echo $this->translate("#First") ?>',
                                        nav_label_prev: '<?php echo $this->translate("#Prev") ?>',
                                        nav_label_last: '<?php echo $this->translate("#Last") ?>',
                                        nav_label_next: '<?php echo $this->translate("#Next") ?>',
                                        nav_label_info: '<?php echo $this->translate("#Showing {0}-{1} of {2} results") ?>'
				});

        $('.page_link').live('click', function(e) {
            e.preventDefault();
            jQuery('html, body').animate({scrollTop: top}, 800);

        return false;
        });
    });
</script>

<div id="conteudo">
<h1><img src="/img/icone_livros.png" align="absmiddle" alt="<?php echo $this->translate("#Works") ?>" /> <?php echo $this->translate("#Works") ?></h1>
<h2 class="categoria"><?php echo $this->pageTitle ?></h2>
<!-- legenda -->
<?php echo $this->listLegend() ?>
<!-- /legenda -->
<div id="page_container">
<ul class="content"
<?php $this->editionsLoop($this->editionsData); ?>
</ul>
<!-- paginacao -->
<div class="page_navigation"></div>
<div class="info_text"></div>
<!-- /paginacao -->
</div>
</div>
