<!-- item de repeticao -->
<li>
<div class="item_livro clearfix">
<?php $this->thumbnailCover($this->coverSrc, $this->exploreUri, $this->title) ?>
<div style="width:450px;" class="float_right"><!-- largura para quando existir thumbnail + class na div -->
<h3><a href="<?php echo $this->exploreUri ?>"><?php echo $this->title ?></a> <?php if (is_array($this->prizes)) { ?><?php echo $this->prizesLoopLegend($this->prizes); ?><?php } ?></h3>
<p><strong><?php echo $this->editorName ?></strong></p>
<p><?php echo $this->summary ?></p>
<p><a href="<?php echo $this->exploreUri ?>" title="$title ?>" class="mais">leia mais</a></p>
</div>
</div>
</li>
<!-- /item de repeticao -->