<?php
$pageData = $this->pageData;
?>
<!-- conteudo -->
<div id="conteudo">
    <h1><?php echo $pageData['title'] ?></h1>

    <h3><?php echo $this->translate('#Question')?></h2>
    <p><?php echo $pageData['question']?></p>
    <h3><?php echo $this->translate('#Answer')?></h2>
    <p><?php echo $pageData['answer']?></p>
    <p> <a href="/admin/question/edit/?id=<?php echo $pageData['id'] ?>"><?php echo $this->translate("#(edit question)") ?></a></p>

    <hr>
        <a href="/admin/question/remove/?id=<?php echo $pageData['id'] ?>"><?php echo $this->translate('#(remove this question!)')?></a></p>
    <a href="/curiosidades/<?php echo $pageData['uri'] ?>"><?php echo $this->translate('#(goto question\'s page)')?></a></p>



</div>
<!-- /conteudo -->
