<div class="clearfix clear_both margin_2">

	<div id="home_column_1">
	
		<h1 class="h1_2">Aulas</h1>

<!-- alerta aulas -->
<?php
if (($this->alertaAulas['planos_a_verificar']) || ($this->alertaAulas['aulas_a_planejar']) || ($this->alertaAulas['aulas_a_relatar']) || ($this->alertaAulas['ultimos_relatos'])) {
?>
	
		<div class="main_box_3">Aten&ccedil;&atilde;o: 
		
<?php
	if ($this->alertaAulas['planos_a_verificar']) {
			
		if($this->alertaAulas['planos_a_verificar'] > 1){
?>
		
<a class="bold" href="<?php echo $this->alertaAulas['link_planos_a_verificar']?>"><?php echo $this->alertaAulas['planos_a_verificar']?> aulas com planos a verificar</a><?php } else {?><a class="bold" href="<?php echo $this->alertaAulas['link_planos_a_verificar']?>">1 aula com planos a verificar</a><?php }} ?>
<?php
	if ($this->alertaAulas['aulas_a_planejar']) {
			
		if($this->alertaAulas['aulas_a_planejar'] > 1){
?>
<?php
			if($this->alertaAulas['planos_a_verificar']){
	
				if(($this->alertaAulas['aulas_a_relatar']) || ($this->alertaAulas['ultimos_relatos'])){
?>
, 
<?php
				} else {
?>

 e 

<?php
				}
			}
?>
<a class="bold" href="<?php echo $this->alertaAulas['link_aulas_a_planejar']?>"><?php echo $this->alertaAulas['aulas_a_planejar']?> aulas a planejar</a><?php } else {?>
<?php
			if($this->alertaAulas['aulas_a_planejar']){
	
				if(($this->alertaAulas['aulas_a_relatar']) || ($this->alertaAulas['ultimos_relatos'])){
?>
, 
<?php
				} else {
?>

 e 

<?php
				}
			}
?>

<a class="bold" href="<?php echo $this->alertaAulas['link_aulas_a_planejar']?>">1 aula a planejar</a><?php }} ?>
<?php
			if ($this->alertaAulas['aulas_a_relatar']) {
			
				if($this->alertaAulas['aulas_a_relatar'] > 1){
?>
<?php
	if(($this->alertaAulas['planos_a_verificar']) || ($this->alertaAulas['aulas_a_planejar'])){
	
		if(($this->alertaAulas['aulas_a_relatar']) || ($this->alertaAulas['ultimos_relatos'])){
?>
, 
<?php
				} else {
?>

 e 

<?php
				}
			}
?>	
<a class="bold" href="<?php echo $this->alertaAulas['link_aulas_a_relatar']?>"><?php echo $this->alertaAulas['aulas_a_relatar']?> aulas a relatar</a><?php } else {?>
<?php
			if(($this->alertaAulas['planos_a_verificar']) || ($this->alertaAulas['aulas_a_planejar'])){
	
				if($this->alertaAulas['ultimos_relatos']){
?>
, 
<?php
				} else {
?>

 e 

<?php
				}
			}
?>
<a class="bold" href="<?php echo $this->alertaAulas['link_aulas_a_relatar']?>">1 aula a relatar</a><?php }} ?>
<?php
			if ($this->alertaAulas['ultimos_relatos']) {
			
				if($this->alertaAulas['ultimos_relatos'] > 1){
?>	
<?php
					if(($this->alertaAulas['planos_a_verificar']) || ($this->alertaAulas['aulas_a_planejar']) || ($this->alertaAulas['aulas_a_relatar'])){
?>

 e 

<?php
					}
?>
<a class="bold" href="<?php echo $this->alertaAulas['link_ultimos_relatos']?>"><?php echo $this->alertaAulas['ultimos_relatos']?> &uacute;ltimos relatos</a><?php } else {?>

<?php
						if(($this->alertaAulas['planos_a_verificar']) || ($this->alertaAulas['aulas_a_planejar']) || ($this->alertaAulas['aulas_a_relatar'])){
?>

 e 

<?php
						}
?>
<a class="bold" href="<?php echo $this->alertaAulas['link_ultimos_relatos']?>">1 &uacute;ltimo relato<?php }} ?></a>.</div>
<?php
}
?>
<!-- /alerta aulas -->

<p class="margin_2"><a class="default_4" href="/planejamento/escola/lista">Listar escolas</a></p>
<?php
					if (isset($this->linksHome['link_monitores'])) {
?>
                <p class="margin_2"><a class="default_4" href="<?php echo $this->linksHome['link_monitores']?>">Listar monitores</a></p>
<?php
					}
?>

<?php
					if (isset($this->linksHome['link_planos_nao_verificados'])) {
?>
                <p class="margin_2"><a class="default_4" href="<?php echo $this->linksHome['link_planos_nao_verificados']?>">Verificar planos</a></p>
<?php
					}
?>

	</div>
	
	<div id="home_column_2">
	
	<h1 class="h1_2">Pano pra manga</h1>

<!-- alerta atividades -->
<?php
if (($this->alertaAtividades['atividades_a_verificar']) || ($this->alertaAtividades['atividades_a_ajustar'])) {
?>
	
		<div class="main_box_3">Aten&ccedil;&atilde;o: 
		
<?php
	if ($this->alertaAtividades['atividades_a_verificar']) {
			
		if($this->alertaAtividades['atividades_a_verificar'] > 1){
?>
		
<a class="bold" href="<?php echo $this->alertaAtividades['link_atividades_a_verificar']?>"><?php echo $this->alertaAtividades['atividades_a_verificar']?> atividades a verificar</a><?php
				} else {
?><a class="bold" href="<?php echo $this->alertaAtividades['link_atividades_a_verificar']?>">1 atividade a verificar</a><?php }} ?>

<?php
			if ($this->alertaAtividades['atividades_a_ajustar']) {
			
				if($this->alertaAtividades['atividades_a_ajustar'] > 1){
?>	
<?php
	if($this->alertaAtividades['atividades_a_verificar']){
?>

 e 

<?php
	}
?>
<a class="bold" href="<?php echo $this->alertaAtividades['link_atividades_a_ajustar']?>"><?php echo $this->alertaAtividades['atividades_a_ajustar']?> atividades a ajustar</a><?php } else {?>

<?php
	if($this->alertaAtividades['atividades_a_verificar']){
?>

 e 

<?php
	}
?>
<a class="bold" href="<?php echo $this->alertaAtividades['link_atividades_a_ajustar']?>">1 atividade a ajustar<?php }} ?></a>.</div>
<?php
}
?>
<!-- /alerta atividades -->

		<p class="margin_2"><a class="default_4" href="/panopramanga/atividade/cria?banco=pano-pra-manga">Criar nova atividade</a></p>
		<p class="margin_2"><a class="default_4" href="/panopramanga/atividade/lista?titulo=pano-pra-manga">Listar atividades</a></p>

<?php
if (isset($this->linksHome['link_gerencia_categorias'])) {
?>
                <p class="margin_2"><a class="default_4" href="<?php echo $this->linksHome['link_gerencia_categorias']?>">Gerenciar categorias</a></p>
<?php
}
?>

<?php
if (isset($this->linksHome['link_atividades'])) {
?>
                <p class="margin_2"><a class="default_4" href="<?php echo $this->linksHome['link_atividades']?>">Minhas atividades</a></p>
<?php
}
?>
		
	</div>
	
</div>