<?php
$pageData = $this->pageData;
?>
<!-- conteudo -->
<div id="conteudo" class="conteudo_1coluna">

<!-- livros -->
<div id="livros_home" class="clearfix">
<div class="coluna1 clearfix">
<img src="img/icone_livros.png" align="top" class="float_left" />
<div class="float_left">
<h2><?php echo $this->translate("#Books") ?></h2>
<h4><?php echo $this->translate("#Stories for all") ?></h4>
</div>
</div>

<ul class="coluna2">
<li><a href="/livros/infantis" title="<?php echo $this->translate("#Children") ?>"><?php echo $this->translate("#Children") ?></a></li>
<li><a href="/livros/juvenis" title="<?php echo $this->translate("#Young people") ?>"><?php echo $this->translate("#Young people") ?></a></li>
<li><a href="/livros/ficção" title="<?php echo $this->translate("#Fiction") ?>"><?php echo $this->translate("#Fiction") ?></a></li>
<li><a href="/livros/ensaios" title="<?php echo $this->translate("#Essays") ?>"><?php echo $this->translate("#Essays") ?></a></li>
</ul>

<div class="coluna3 clearfix">
<div class="float_left">
<h3><a href="<?php echo $pageData['worksSpecialUri']?>" title="<?php echo $pageData['worksSpecialTitle'] ?>"><?php echo $pageData['worksSpecialTitle']?></h3>
<p><?php echo $pageData['worksSpecialSummary']?></p>
<p><a href="<?php echo $pageData['worksSpecialUri']?>" title="<?php echo $this->translate("#more about") ?>" class="mais"> <?php echo $this->translate("#more about") ?></a></p>
</div>
<a href="<?php echo $pageData['worksSpecialUri']?>" class="float_right" title="<?php echo $pageData['worksSpecialTitle']?>"><img src="<?php echo $pageData['worksSpecialImageUri']?>" alt="<?php echo $pageData['worksSpecialTitle']?>" /></a>
</div>

</div>
<!-- /livros -->

<!-- novidades -->
<div id="novidades_home">

<div class="coluna1 clearfix">
<img src="img/icone_novidades.png" align="top" class="float_left" />
<div class="float_left">
<h2>Novidades</h2>
<h4>O que a Ana anda aprontando por a&iacute;</h4>
</div>
</div>

<div class="coluna2">
<!-- item de repeticao -->
<h3><a href="" title="">Silenciosa Algazarra sera tema de conversa com professores na PUC/RJ</a></h3>
<p>28.08.2012 | <a href="" title=""><strong>2 coment&aacute;rios</strong></a></p>
<!-- /item de repeticao -->
<!-- item de repeticao -->
<h3><a href="" title="">Ana Maria Machado e Ruth Rocha no Salao do Livro Infantil em Belo Horizonte</a></h3>
<p>28.08.2012 | <a href="" title=""><strong>Comente</strong></a></p>
<!-- /item de repeticao -->
</div>

</div>
<!-- /novidades -->

<!-- biografia -->
<div id="biografia_home">

<div class="coluna1 clearfix">
<img src="img/icone_biografia.png" align="top" class="float_left" />
<div class="float_left">
<h2>Biografia</h2>
<h4>Um resumo da vida e obra da artista</h4>
</div>
</div>

<div class="coluna2">
<p>Meu nome e Ana Maria Machado e eu vivo inventando historias. E dessas que eu escrevo, algumas viram livros. </p>
<p><a href="" title="Mais" class="mais">mais</a></p>
</div>

</div>
<!-- /biografia -->

<!-- contato -->
<div id="contato_home">

<div class="coluna1 clearfix">
<img src="img/icone_contato.png" align="top" class="float_left" />
<div class="float_left"><h2>Contato</h2>
<h4>Tire suas d&uacute;vidas ou entre em contato</h4>
</div>
</div>

<div class="coluna2">
<p>A resposta para a sua duvida pode estar aqui:</p>
<form>
<select class="duvidas">
<option selected="selected">Selecione</option>
</select>
</form>
</div>

</div>
<!-- /contato -->

</div>
<!-- /conteudo -->
