<?php
$pageData = $this->pageData;
$worksData = $pageData['worksData'];
$blogData = $pageData['blogData'];
$bioData = $pageData['bioData'];
$faqData = $pageData['faqData'];
?>
<!-- conteudo -->
<div id="conteudo" class="conteudo_1coluna">

<!-- livros -->
<div id="livros_home" class="clearfix">
<div class="coluna1 clearfix">
<a href="/livros" title="<?php echo $this->translate("#Books") ?>"><img src="img/icone_livros.png" align="top" class="float_left" style="border-style: none"/></a>
<div class="float_left">
<h2><a href="/livros" title="<?php echo $this->translate("#Books") ?>"><?php echo $this->translate("#Books") ?></a></h2>
<h4><a href="/livros" title="<?php echo $this->translate("#Books") ?>"><?php echo $this->translate("#Stories for all") ?></a></h4>
</div>
</div>

<ul class="coluna2">
<li><a href="/livros/infantis" title="<?php echo $this->translate("#Children") ?>"><?php echo $this->translate("#Children") ?></a></li>
<li><a href="/livros/juvenis" title="<?php echo $this->translate("#Young people") ?>"><?php echo $this->translate("#Young people") ?></a></li>
<li><a href="/livros/ficcao" title="<?php echo $this->translate("#Fiction") ?>"><?php echo $this->translate("#Fiction") ?></a></li>
<li><a href="/livros/ensaios" title="<?php echo $this->translate("#Essays") ?>"><?php echo $this->translate("#Essays") ?></a></li>
</ul>

<div class="coluna3 clearfix">
<div class="float_left">
<h3><a href="<?php echo $worksData['worksSpecialUri']?>" title="<?php echo $worksData['worksSpecialTitle'] ?>"><?php echo $worksData['worksSpecialTitle']?></h3>
<p><?php echo $worksData['worksSpecialSummary']?></p>
<p><a href="<?php echo $worksData['worksSpecialUri']?>" title="<?php echo $this->translate("#more about") ?>" class="mais"> <?php echo $this->translate("#more about") ?></a></p>
</div>
<a href="<?php echo $worksData['worksSpecialUri']?>" class="float_right" title="<?php echo $worksData['worksSpecialTitle']?>"><img src="<?php echo $worksData['worksSpecialImageUri']?>" alt="<?php echo $worksData['worksSpecialTitle']?>" /></a>
</div>

</div>
<!-- /livros -->

<!-- novidades -->
<div id="novidades_home">

<div class="coluna1 clearfix">
<a href="/novidades" title="<?php echo $this->translate("#Blog title") ?>"><img src="img/icone_novidades.png" align="top" class="float_left" /></a>
<div class="float_left">
<h2><a href="/novidades" title="<?php echo $this->translate("#Blog title") ?>"><?php echo $this->translate("#Blog title") ?></h2>
<h4><a href="/novidades" title="<?php echo $this->translate("#Blog title") ?>"><?php echo $this->translate("#Home blog tagline") ?></a></h4>
<h4></h4>
</div>
</div>

<div class="coluna2">
<!-- item de repeticao -->
<h3><a href="<?php echo $this->translate("/post") ?>/<?php echo $blogData['firstPostUri']?>" title="<?php echo $blogData['firstPostTitle']?>"><?php echo $blogData['firstPostTitle']?></a></h3>
<p><?php echo $blogData['firstPostDate']?></p>
<!-- /item de repeticao -->
<!-- item de repeticao -->
<h3><a href="<?php echo $this->translate("/post") ?>/<?php echo $blogData['secondPostUri']?>" title="<?php echo $blogData['secondPostTitle']?>"><?php echo $blogData['secondPostTitle']?></a></h3>
<p><?php echo $blogData['secondPostDate']?></p>
<!-- /item de repeticao -->
</div>

</div>
<!-- /novidades -->

<!-- biografia -->
<div id="biografia_home">

<div class="coluna1 clearfix">
<a href="/biografia" title="<?php echo $this->translate("#Biography") ?>"><img src="img/icone_biografia.png" align="top" class="float_left" /></a>
<div class="float_left">
<h2><a href="/biografia" title="<?php echo $this->translate("#Biography") ?>"><?php echo $this->translate("#Biography") ?></h2>
<h4><a href="/biografia" title="<?php echo $this->translate("#Biography") ?>"><?php echo $this->translate("#Home biography tagline") ?></a></h4>
</div>
</div>

<div class="coluna2">
<p><?php echo $bioData['excerpt']?></p>
<p><a href="/biografia" title="<?php echo $this->translate("#more about") ?>" class="mais"><?php echo $this->translate("#more about") ?></a></p>
</div>

</div>
<!-- /biografia -->

<!-- contato -->
<div id="contato_home">

<div class="coluna1 clearfix">
<a href="/respostas" title="<?php echo $this->translate("#Faq title") ?>"><img src="img/icone_contato.png" align="top" class="float_left" /></a>
<div class="float_left"><h2><a href="/respostas" title="<?php echo $this->translate("#Faq title") ?>"><?php echo $this->translate("#Frequently asked questions") ?></a></h2>
<h4><a href="/respostas" title="<?php echo $this->translate("#Faq title") ?>"><?php echo $this->translate("#Get answers here") ?></a></h4>
</div>
</div>

<div class="coluna2">
<p><?php echo $this->translate("#Answers to frequently asked questions:") ?></p>
<form>
<select class="duvidas" id="gotoFaq">
<option selected="selected"><?php echo $this->translate("#(choose)") ?></option>

<?php
$this->faqsLoop($faqData);
?>
</select>
</form>
</div>

</div>
<!-- /contato -->

</div>
<!-- /conteudo -->
        <script type="text/javascript">

        $(document).ready(function(){

            $('#gotoFaq').change(function(){
                var current = $(this).val();

                window.location = '/respostas/' + current;

            });
        });

        </script>
