<div class="clearfix clear_both">

	<div class="home_box">
		<p class="caption_2">Planejamento</p>
		
<?php
if (isset($this->linksHome['link_cadastra_escola'])) {
?>
		
		<p class="border_1"><a class="default_4" href="<?php echo $this->linksHome['link_cadastra_escola']?>">Cadastrar escola</a></p>
		
<?php
}
?>

<?php
if (isset($this->linksHome['link_cadastra_turma'])) {
?>
		
		<p class="border_1"><a class="default_4" href="<?php echo $this->linksHome['link_cadastra_turma']?>">Cadastrar turma</a></p>
		
<?php
}
?>

<?php
if (isset($this->linksHome['link_cadastra_horario'])) {
?>
		
        <p class="border_1"><a class="default_4" href="<?php echo $this->linksHome['link_cadastra_horario']?>">Cadastrar horário</a></p>
		
<?php
}
?>
		
        <p class="border_1"><a class="default_4" href="/planejamento/escola/lista">Listar escolas</a></p>

	</div>

</div>