<div id="breadcrumb">Ocorreu um erro</div>
  
  <h1>Erro</h1>
  
  <div style=" width:990px; overflow:scroll;">
  
  <p class="margin_9"><?php echo $this->message ?></p>

  <?php if (isset($this->exception)): ?>
  
  <p class="margin_10">Exception information:</p>
  <p class="margin_9">
      <b>Message:</b> <?php echo $this->exception->getMessage() ?>
  </p>

  <p class="margin_10">Stack trace:</p>
  <pre><?php echo $this->exception->getTraceAsString() ?>
  </pre>

  <p class="margin_12">Request Parameters:</p>
  <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
  </pre>

  <?php endif ?>
  
  </div>