<!-- item de repeticao -->
<div class="item_livro clearfix">
<?php $this->cover($this->coverSrc, $this->exploreUri) ?>
<div style="width:450px;" class="float_right"><!-- largura para quando existir thumbnail + class na div -->
<h3><a href="<?php echo $this->exploreUri ?>"><?php echo $this->title ?></a> <a href=""><img src="/img/detalhe_premio.png" align="absmiddle" /></a><a href=""><img src="/img/detalhe_premio.png" align="absmiddle" /></a><a href=""><img src="/img/detalhe_premio.png" align="absmiddle" /></a></h3>
<p><strong><?php echo $this->editorName ?></strong></p>
<p><?php echo $this->summary ?></p>
<p><a href="<?php echo $this->exploreUri ?>" title="$title ?>" class="mais">leia mais</a></p>
</div>
</div>
<!-- /item de repeticao -->