<div id="breadcrumb"><?php echo $this->breadcrumb?></div>

<h1><?php echo $this->tituloPagina?></h1>

<?php
if (isset($this->monitorPagina)) {

    if (!$this->monitorPagina['comandoApagarEnviado']) {
?>

<br />
Voc&ecirc; tem certeza que deseja inativar o monitor <span class="bold"><?php echo $this->monitorPagina['nome']?> <?php echo $this->monitorPagina['sobrenome']?></span> ?<br /><br /><br />

<form method="post" name="frmApaga" action="<?php echo $_SERVER["REQUEST_URI"]?>" enctype="multipart/form-data" accept-charset="utf-8">

<input type="hidden" name="etapaEnvio" value="1"/>

<input name="submit" id="submit" type="submit" value="Confirmar" alt="Confirmar" title="Confirmar" class="button_2" />&nbsp;&nbsp;
<input name="cancelar" id="cancelar" type="button" value="Cancelar" alt="Cancelar" title="Cancelar" class="button_2" onclick="javascript:history.go(-1);"/>

</form>
<br />

<?php
    } else {
?>

<span><?php echo $this->monitorPagina['mensagem_retorno']?></span><br /><br />

<?php
    }
}
?>