<div id="breadcrumb"><?php echo $this->breadcrumb?></div>

<h1><?php echo $this->tituloPagina?></h1>

<?php
if (isset($this->conjuntoMonitores)) {
?>
	
<?php
    foreach ($this->conjuntoMonitores as $idStr => $dadosMonitor) {
?>


<p class="margin_10 bold"><?php echo $dadosMonitor['nome']?></p>

<p class="margin_9">

<?php
		if($dadosMonitor['link_horarios']){
?>

<a class="default_4" href="<?php echo $dadosMonitor['link_horarios']?>">visualizar hor&aacute;rios</a>&nbsp; 

<?php
		}
?>

<a class="default_4" href="<?php echo $dadosMonitor['link_aulas']?>">visualizar aulas</a>

</p>

<?php
	}
	
} else {
?>

<p class="margin_9">Nenhum monitor at&eacute; o momento.</p>

<?php
}
?>