<?php
$pageData = $this->pageData;
?>
<!-- conteudo -->
<div id="conteudo">
    <h1><?php echo $pageData['title'] ?></h1>

    <h3><?php echo $this->translate('#Content')?></h2>
    <p><?php echo $pageData['content']?></p>

    <h3><?php echo $this->translate('#Keywords')?></h2>
    <?php echo $this->keywordsLoop($pageData['keywords']) ?>
    <p><a href="/admin/post/create-keyword/?id=<?php echo $pageData['id'] ?>"><?php echo $this->translate("#Add keyword") ?></a></p>


    <p> <a href="/admin/post/edit/?id=<?php echo $pageData['id'] ?>"><?php echo $this->translate("#(edit post)") ?></a></p>

    <hr>
        <a href="/admin/post/remove/?id=<?php echo $pageData['id'] ?>"><?php echo $this->translate('#(remove this post!)')?></a></p>
    <a href="/curiosidades/<?php echo $pageData['uri'] ?>"><?php echo $this->translate('#(goto post\'s page)')?></a></p>



</div>
<!-- /conteudo -->
