<?php
$pageData = $this->pageData;
?>
<!-- box livros -->
<div class="box_detalhe"></div>

<div class="box">

<h2><?php print $this->translate("#Categories") ?></h2>
    <?php echo $this->categoriesLoop($pageData['categories']) ?>



<!-- item de repeticao -->
<!--<div class="item_box">
<h3 class="categorias"><a href="">Professor</a></h3>
</div>-->
<!-- /item de repeticao -->

<!-- item de repeticao -->
<!--<div class="item_box" style="border:none;margin-bottom:0;">
<h3 class="categorias" style="margin-bottom:0;"><a href="">Agenda</a></h3>
</div>-->
<!-- /item de repeticao -->

</div>
<!-- /box livros -->