<!-- box livros -->
<div class="box_detalhe"></div>

<div class="box">

<h2>Categorias</h2>

<!-- item de repeticao -->
<div class="item_box">
<h3 class="categorias"><a href="">Imprensa</a></h3>
</div>
<!-- /item de repeticao -->

<!-- item de repeticao -->
<div class="item_box">
<h3 class="categorias"><a href="">Leitura</a></h3>
</div>
<!-- /item de repeticao -->

<!-- item de repeticao -->
<div class="item_box">
<h3 class="categorias"><a href="">Professor</a></h3>
</div>
<!-- /item de repeticao -->

<!-- item de repeticao -->
<div class="item_box" style="border:none;margin-bottom:0;">
<h3 class="categorias" style="margin-bottom:0;"><a href="">Agenda</a></h3>
</div>
<!-- /item de repeticao -->

</div>
<!-- /box livros -->