<!-- box busca -->
<div class="box">

<h2><?php echo $this->translate("#Virtual Exposition") ?></h2>
<div id="box2">
<p class="clear_both"><a href="/expo/primeiros-passos" alt="Primeiros Passos">Primeiros Passos</a></p>
<p class="clear_both"><a href="/expo/pintando-o-caneco" alt="Pintando o Caneco">Pintando o Caneco</a></p>
<p class="clear_both"><a href="/expo/aquele-abraco" alt="Aquele Abraço">Aquele Abraço</a></p>
<p class="clear_both"><a href="/expo/agora-para-ficar" alt="Agora Para Ficar">Agora Para Ficar</a></p>
<p class="clear_both"><a href="/expo/mil-historias" alt="Mil Histórias">Mil Histórias</a></p>
<p class="clear_both"><a href="/expo/tempo-de-colheita" alt="Tempo de Colheita">Tempo de Colheita</a></p>
</div>

</div>
<!-- /box busca -->