<div id="rodape_detalhe"></div>

<div id="rodape">

<div class="box_tag">
    <p>Nuvem de Tags</p>
    <p><a href="" class="tag_1">Escola</a>  <a href="" class="tag_3">Palestra</a>  <a href="" class="tag_2">Brincadeira de Sombra</a>  <a href="" class="tag_4">Biblioteca</a></p>
</div>

<ul class="box_rodape">
	<li><a href="/livros" class="uppercase" title="Livros">Livros</a></li>
<li><a href="/livros/infantis" title="<?php echo $this->translate("#Children") ?>"><?php echo $this->translate("#Children") ?></a></li>
<li><a href="/livros/juvenis" title="<?php echo $this->translate("#Young people") ?>"><?php echo $this->translate("#Young people") ?></a></li>
<li><a href="/livros/ficcao" title="<?php echo $this->translate("#Fiction") ?>"><?php echo $this->translate("#Fiction") ?></a></li>
<li><a href="/livros/ensaios" title="<?php echo $this->translate("#Essays") ?>"><?php echo $this->translate("#Essays") ?></a></li>
</ul>

<ul class="box_rodape" style="width:190px;">
    <li><a href="/novidades" class="uppercase" title="<?php echo $this->translate("#Blog title") ?>"><?php echo $this->translate("#Blog title") ?></a></li>
    <li>Categorias</li>
    <li><a href="">Professor</a></li>
    <li><a href="">Agenda</a></li>
    <li><a href="">Academia Brasileira de Letras</a></li>
    <li><a href="">Exposi&ccedil;&atilde;o Virtual</a></li>
</ul>

<ul class="box_rodape" style="width:70px;margin-left:0;">
	<li><a href="/biografia" class="uppercase" title="Biografia">Biografia</a></li>
	<li><a href="/contato" class="uppercase" title="Contato">Contato</a></li>
</ul>

<p class="clear_both">&copy;2013 Ana Maria Machado. Todos os direitos reservados.</p>

</div>
<?php echo $this->panel() ?>
