<?php
$pageData = $this->pageData;
?>
<div id="rodape_detalhe"></div>

<div id="rodape">

<div class="box_tag">
    <p><?php echo $this->translate("#Tag cloud") ?></p>
    <p>
        <?php foreach ($pageData['tags'] as $key => $arrayTag) { ?>
        <a href="/tag/<?php echo $arrayTag['uri'] ?>" class="<?php echo $arrayTag['class'] ?>"><?php echo $arrayTag['term'] ?></a>
        <?php } ?>
    </p>
</div>

<ul class="box_rodape">
<li><a href="<?php print $this->translate("/works") ?>" class="uppercase" title="<?php echo $this->translate("#Books") ?>"><?php echo $this->translate("#Books") ?></a></li>
<li><a href="<?php print $this->translate("/works/children") ?>" title="<?php echo $this->translate("#Children") ?>"><?php echo $this->translate("#Children") ?></a></li>
<li><a href="<?php print $this->translate("/works/young") ?>" title="<?php echo $this->translate("#Young people") ?>"><?php echo $this->translate("#Young people") ?></a></li>
<li><a href="<?php print $this->translate("/works/fiction") ?>" title="<?php echo $this->translate("#Fiction") ?>"><?php echo $this->translate("#Fiction") ?></a></li>
<li><a href="<?php print $this->translate("/works/essays") ?>" title="<?php echo $this->translate("#Essays") ?>"><?php echo $this->translate("#Essays") ?></a></li>
<li><a href="<?php print $this->translate("/works/series") ?>"><?php print $this->translate("#Series") ?></a></li>
</ul>

<ul class="box_rodape">
    <li><a href="/curiosidades" class="uppercase" title="<?php echo $this->translate("#Blog title") ?>"><?php echo $this->translate("#Blog title") ?></a></li>
    <?php echo $this->categoriesLoopLi($pageData['categories']) ?>
</ul>

<ul class="box_rodape">
	<li><a href="/biografia" class="uppercase" title="<?php echo $this->translate("#Biography") ?>"><?php echo $this->translate("#Biography") ?></a></li>
</ul>

<ul class="box_rodape">
	<li><a href="/respostas" class="uppercase" title="<?php echo $this->translate("#Frequently asked questions") ?>"><?php echo $this->translate("#Frequently asked questions") ?></a></li>
</ul>

<p class="clear_both"><?php echo $this->translate("#Copyright notice") ?></p>

</div>
<?php echo $this->panel() ?>
