<div id="rodape_detalhe"></div>

<div id="rodape">

<div class="box_tag">
    <p>Nuvem de Tags</p>
    <p><a href="" class="tag_1">Escola</a>  <a href="" class="tag_3">Palestra</a>  <a href="" class="tag_2">Brincadeira de Sombra</a>  <a href="" class="tag_4">Biblioteca</a></p>
</div>

<ul class="box_rodape">
	<li><a href="/livros" class="uppercase" title="Livros">Livros</a></li>
	<li>Para gente crescendo</li>
    <li><a href="">Leitores Iniciantes</a></li>
    <li><a href="">Primeiras Hist&oacute;rias</a></li>
    <li><a href="">Alguma Habilidade de Leitura</a></li>
	<li style="margin-top:20px;">Para gente grande</li>
    <li><a href="">Romances</a></li>
    <li><a href="">Ensaios</a></li>
</ul>

<ul class="box_rodape" style="width:190px;">
    <li><a href="/novidades" class="uppercase" title="Novidades">Novidades</a></li>
    <li>Categorias</li>
    <li><a href="">Premia&ccedil;&otilde;es</a></li>
    <li><a href="">Imprensa</a></li>
    <li><a href="">Leitura</a></li>
    <li><a href="">Professor</a></li>
    <li><a href="">Agenda</a></li>
    <li><a href="">Academia Brasileira de Letras</a></li>
    <li><a href="">Exposi&ccedil;&atilde;o Virtual</a></li>
</ul>

<ul class="box_rodape" style="width:70px;margin-left:0;">
	<li><a href="/biografia" class="uppercase" title="Biografia">Biografia</a></li>
	<li><a href="/contato" class="uppercase" title="Contato">Contato</a></li>
</ul>

<p class="clear_both">&copy;2013 Ana Maria Machado. Todos os direitos reservados.</p>

</div>
<?php echo $this->panel() ?>
