<script type="text/javascript" language="javascript">
<!--ABRIR E FECHAR BOXES-->
var aberto = false;
function abreBox() {

	if(!aberto) {
		document.getElementById("box1").style.display = "block";
		document.getElementById("box2").style.display = "none";
		aberto = true;
	}
	else {
		aberto = false;
	}
}

function fechaBox() {
	if(aberto) {
		document.getElementById("box1").style.display = "none";
		document.getElementById("box2").style.display = "block";
		aberto = false;
	}
document.onclick = fechaBox1;
}
<!--/ABRIR E FECHAR BOXES-->
</script>

<!-- box busca -->
<div class="box">

<h2><?php echo $this->translate("#Search for books") ?></h2>
<p><small><?php echo $this->translate("#Use field below to search and click on one of the suggested titles") ?></small>
    </p>
<form>
<input type="text" id="search_topic" class="busca display_block float_left" /><input id='submitSearch' type="button" value="Ok" class="display_block float_right" />
</form>

<div id="box2">
<p class="clear_both"><a href="Javascript:abreBox()" alt="busca avan&ccedil;ada">busca avan&ccedil;ada <img src="/img/icone_abrir.png" align="absmiddle" alt="busca avan&ccedil;ada" /></a></p>
</div>

<!-- busca avancada -->
<div id="box1" style="display:none">

<p class="clear_both"><a href="Javascript:fechaBox()" alt="busca avan&ccedil;ada">busca avan&ccedil;ada <img src="/img/icone_fechar.png" align="absmiddle" alt="busca avan&ccedil;ada" /></a></p>

<form>
<select class="busca">
<option selected="selected">Selecione</option>
</select>

<select class="busca">
<option selected="selected">Selecione</option>
</select>

<select class="busca">
<option selected="selected">Selecione</option>
</select>

<select class="busca">
<option selected="selected">Selecione</option>
</select>
</form>
</div>
<!-- /busca avancada -->

</div>
<!-- /box busca -->
<script>
$(document).ready(function() {
    $("#submitSearch").click(function(){

    });
});

$(function() {

    $("#search_topic").autocomplete({
        source: "/works/index/autocomplete",
        minLength: 2,
        select: function(event, ui) {
            var url = ui.item.id;
            if(url != '#') {
                location.href = '/livro/' + url;
            }
        },

        html: true, // optional (jquery.ui.autocomplete.html.js required)

      // optional (if other layers overlap autocomplete list)
        open: function(event, ui) {
            $(".ui-autocomplete").css("z-index", 1000);
        }
    });

});


</script>

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/jquery-ui.js"></script>
<script type="text/javascript" src="/js/jquery.ui.autocomplete.html.js"></script>
