<!-- box livros -->
<div class="box_detalhe_livros"></div>

<div class="box">

<h2><?php print $this->translate("#Works") ?></h2>


<!-- item de repeticao -->
<div class="item_box">
<h3 class="categorias"><a href="<?php print $this->translate("/works/children") ?>"><?php print $this->translate("#Children") ?></a></h3>
</div>
<!-- /item de repeticao -->

<!-- item de repeticao -->
<div class="item_box">
<h3 class="categorias"><a href="<?php print $this->translate("/works/young") ?>"><?php print $this->translate("#Young") ?></a></h3>
</div>
<!-- /item de repeticao -->

<!-- item de repeticao -->
<div class="item_box">
<h3 class="categorias"><a href="<?php print $this->translate("/works/fiction") ?>"><?php print $this->translate("#Fiction") ?></a></h3>
</div>
<!-- /item de repeticao -->

<!-- item de repeticao -->
<div class="item_box">
<h3 class="categorias"><a href="<?php print $this->translate("/works/essays") ?>"><?php print $this->translate("#Essays") ?></a></h3>
</div>
<!-- /item de repeticao -->

<!-- item de repeticao -->
<div class="item_box" style="border:none;margin-bottom:0;">
<h3 class="categorias" style="margin-bottom:0;"><a href="<?php print $this->translate("/works/series") ?>"><?php print $this->translate("#Series") ?></a></h3>
</div>
<!-- /item de repeticao -->

</div>
<!-- /box livros -->