<!-- box livros -->
<div class="box_detalhe_livros"></div>

<div class="box">

<h2><?php print $this->translate("#Works") ?></h2>


<!-- item de repeticao -->
<div class="item_box">
<h3 class="categorias"><a href="">Infantis</a></h3>
</div>
<!-- /item de repeticao -->

<!-- item de repeticao -->
<div class="item_box">
<h3 class="categorias"><a href="">Juvenis</a></h3>
</div>
<!-- /item de repeticao -->

<!-- item de repeticao -->
<div class="item_box">
<h3 class="categorias"><a href="">Ficção</a></h3>
</div>
<!-- /item de repeticao -->

<!-- item de repeticao -->
<div class="item_box" style="border:none;margin-bottom:0;">
<h3 class="categorias" style="margin-bottom:0;"><a href="">Ensaios</a></h3>
</div>
<!-- /item de repeticao -->

</div>
<!-- /box livros -->