<?php
$pageData = $this->pageData;
?>
<!-- conteudo -->
<div id="conteudo">

<h1><img src="/img/icone_livros.png" align="absmiddle" alt="Livros" /> Livros</h1>

<a href="<?php echo $pageData['bigImageUri']?>"><img src="<?php echo $pageData['mediumImageUri']?>" class="float_left livro" /></a>
<h3><?php echo $pageData['title']?></h3>
<p><strong><?php echo $pageData['editorName']?></strong></p>
<p><?php echo $pageData['description']?></p>

<p><small>
<?php if (isset($pageData['collectionName'])) { ?>
<?php echo $pageData['collectionName']?><br />
<?php } ?>
<?php if (isset($pageData['ilustratorName'])) { ?>
<?php echo $pageData['ilustratorName']?><br />
<?php } ?>
<?php if (isset($pageData['isbn'])) { ?>
<?php echo $pageData['isbn']?><br />
<?php } ?>
<?php if (isset($pageData['pages'])) { ?>
<?php echo $pageData['pages']?><br />
<?php } ?>
</small></p>

<form>
<input type="submit" value="Comprar online" />
</form>

<!-- mais sobre o livro -->
<div class="box_conteudo" style="margin-top:20px;"><img src="/img/icone_livro_mais.png" align="absmiddle" /> <a href=""><strong>Mais curiosidades sobre este livro</strong></a></div>
<!-- /mais sobre o livro -->

<!-- premios -->
<div class="box_conteudo">
<h4 class="premio">Pr&ecirc;mios</h4>
<ul>
<li>1997 - Pr&ecirc;mio Am&eacute;ricas (Melhores livros latinos nos EUA)</li>
<li>1996 - Altamente Recomend&aacute;vel, Fundalectura, Bogot&aacute;, Col&ocirc;mbia</li>
<li>1996 - Melhor Livro Infantil Latino-americano, ALIJA - Buenos Aires></li>
<li>1995 - Pr&ecirc;mio Melhores do Ano, Biblioteca Nacional da Venezuela</li>
<li>1988 - Pr&ecirc;mio Bienal de S&atilde;o Paulo, Bienal de S&atilde;o Paulo (Men&ccedil;&atilde;o Honrosa - Uma das Cinco Melhores Obras do Bi&ecirc;nio)</li>
</ul>
</div>
<!-- /premios -->

</div>
<!-- /conteudo -->
