<!-- item de repeticao -->
<div class="item clearfix">
<div style="width:600px;" class="float_right"><!-- largura para quando não existir thumbnail -->
<h3><a href="<?php echo $this->uri ?>"><?php echo $this->title ?></a></h3>
<p><?php echo $this->publicationDate ?> | <a href="<?php echo $this->categoryUri ?>" title="<?php echo $this->categoryTerm ?>"><strong><?php echo $this->categoryTerm ?></strong></a><!-- | <a href="" title=""><img src="/img/icone_comentario.png" align="absmiddle" /> <strong>2 coment&aacute;rios</strong></a>--></p>
<p><?php echo $this->content ?></p>
<!--<p><a href="" title="mais novidades" class="mais">leia mais</a></p>-->
</div>
</div>
<!-- /item de repeticao -->