<!-- item de repeticao -->
<div class="item clearfix">
<div style="width:600px;" class="float_right"><!-- largura para quando não existir thumbnail -->
<h3><a href="<?php echo $this->translate("/post") ?>/<?php echo $this->uri ?>"><?php echo $this->title ?></a></h3>
<p><?php echo $this->publicationDate ?> | <?php echo $this->categoryHrefTerm($this->categoryModel) ?><!-- | <a href="" title=""><img src="/img/icone_comentario.png" align="absmiddle" /> <strong>2 coment&aacute;rios</strong></a>--></p>
<?php echo $this->content ?><a href="<?php echo $this->translate("/post") ?>/<?php echo $this->uri ?>"><?php echo $this->translate("#(more)") ?></a>
<!--<p><a href="" title="mais curiosidades" class="mais">leia mais</a></p>-->
</div>
</div>
<!-- /item de repeticao -->