<div id="breadcrumb"><?php echo $this->breadcrumb?></div>

<h1><?php echo $this->tituloPagina?></h1>

<?php
if ($this->usuarioPagina['senhaEnviada']) {

    if (!$this->usuarioPagina['senhaEnviadaComErro']) {
?>

<!-- success -->
<p class="text_success"><?php echo $this->translate('Sua senha foi alterada com sucesso.')?></p>
<!-- /success -->

<?php
    } else {
?>

<!-- result -->
<p class="text_error"><?php echo $this->translate('erro')?> <?php echo $this->usuarioPagina['Houve um erro no cadastro da sua senha.']?></p>
<!-- /result -->

<?php
    }
}

if ((!$this->usuarioPagina['senhaEnviada']) || (($this->usuarioPagina['senhaEnviada']) && ($this->usuarioPagina['senhaEnviadaComErro']))) {
?>

<form method="post" name="frmUsuario" action="<?php echo $_SERVER["REQUEST_URI"]?>" enctype="multipart/form-data" accept-charset="utf-8">

<p>* <?php echo $this->translate('campos_obrigatorios')?></p><br /><br />

<label for="txtAlteraSenhaUsuario"><?php echo $this->translate('senha')?>*</label>
<input name="txtAlteraSenhaUsuario" type="password" class="single" id="txtAlteraSenhaUsuario" value="<?php echo $this->usuarioPagina['senha']?>" maxlength="10"/>

<label for="txtAlteraRepeteSenha"><?php echo $this->translate('repeticao_senha')?>*</label>
<input name="txtAlteraRepeteSenha" type="password" class="single" id="txtAlteraRepeteSenha" value="<?php echo $this->usuarioPagina['senha_repetida']?>" maxlength="10"/>

<div class="margin_1">
<input type="hidden" name="etapaEnvio" value="1"/>
<input name="submit" id="submit" type="submit" value="<?php echo $this->translate('enviar')?>" alt="<?php echo $this->translate('enviar')?>" title="<?php echo $this->translate('enviar')?>" class="button_2" />
</div>

</form>

<?php
}
?>