<div id="breadcrumb"><?php echo $this->breadcrumb?></div>

<h1><?php echo $this->tituloPagina?></h1>

<?php
if (isset($this->ativaUsuario)) {
?>

<p class="margin_10"><?php echo $this->translate('ola')?> <?php echo $this->nomeUsuario?>.</p>

<p class="margin_9"><?php echo $this->translate('intro_ativacao')?></p>

<?php
	if (!$this->ativaUsuario['usuarioEnviado']) {

            if ($this->ativaUsuario['usuarioComErro']) {
?>

<p class="text_error"><?php echo $this->translate('erro')?> <?php echo $this->ativaUsuario['mensagem_erro_usuario']?></p>

<?php
            }

    } else if (($this->ativaUsuario['usuarioEnviado']) && ($this->ativaUsuario['usuarioComErro'])) {
?>

<p class="text_error"><?php echo $this->translate('erro')?> <?php echo $this->ativaUsuario['mensagem_erro_usuario']?></p>

<?php
    }
}
?>

<?php
if (!$this->escondeForm) {
?>

<form method="post" name="frmUsuario" action="<?php echo $_SERVER["REQUEST_URI"]?>" enctype="multipart/form-data" accept-charset="utf-8">

<p>* <?php echo $this->translate('campos_obrigatorios')?></p><br />

<label for="txtAtivaSenhaUsuario"><?php echo $this->translate('senha')?>*</label>
<input name="txtAtivaSenhaUsuario" type="password" class="single" id="txtAtivaSenhaUsuario" value="<?php echo $this->ativaUsuario['senha']?>" maxlength="10"/>

<label for="txtAtivaRepeteSenha"><?php echo $this->translate('repeticao_senha')?>*</label>
<input name="txtAtivaRepeteSenha" type="password" class="single" id="txtAtivaRepeteSenha" value="<?php echo $this->ativaUsuario['senha_repetida']?>" maxlength="10"/>

<div class="margin_1">
<input type="hidden" name="etapaEnvio" value="1"/>
<input name="submit" id="submit" type="submit" value="<?php echo $this->translate('enviar')?>" alt="<?php echo $this->translate('enviar')?>" title="<?php echo $this->translate('enviar')?>" class="button_2" />
</div>

</form>

<?php
}
?>