<div id="breadcrumb"><?php echo $this->breadcrumb?></div>

<h1><?php echo $this->tituloPagina?></h1>

<?php
if ($this->novoUsuario['usuarioEnviado']) {

    if (!$this->novoUsuario['usuarioEnviadoComErro']) {
?>

<!-- success -->
<p class="text_success"><?php echo $this->translate('sucesso_cria_usuario')?></p>
<!-- /success -->

<?php
    } else {
?>

<!-- result -->
<p class="text_error"><?php echo $this->translate('erro')?> <?php echo $this->novoUsuario['mensagem_erro_usuario']?></p>
<!-- /result -->

<?php
    }
}

if ((!$this->novoUsuario['usuarioEnviado']) || (($this->novoUsuario['usuarioEnviado']) && ($this->novoUsuario['usuarioEnviadoComErro']))) {
?>

<form method="post" name="frmUsuario" action="<?php echo $_SERVER["REQUEST_URI"]?>" enctype="multipart/form-data" accept-charset="utf-8">

<p>* <?php echo $this->translate('campos_obrigatorios')?></p><br /><br />

<label for="txtNome"><?php echo $this->translate('nome')?>*</label>
<input name="txtNome" id="txtNome" type="text" class="single" value="<?php echo $this->novoUsuario['nome']?>" maxlength="120"/>

<label for="txtSobrenome"><?php echo $this->translate('sobrenome')?>*</label>
<input name="txtSobrenome" id="txtSobrenome" type="text" class="single" value="<?php echo $this->novoUsuario['sobrenome']?>" maxlength="120"/>

<label for="txtApelido"><?php echo $this->translate('apelido')?>*</label>
<input name="txtApelido" type="text" class="single" id="txtApelido" value="<?php echo $this->novoUsuario['apelido']?>" maxlength="80"/>

<label for="txtEmail"><?php echo $this->translate('email')?>*</label>
<input name="txtEmail" type="text" class="single" id="txtEmail" value="<?php echo $this->novoUsuario['email']?>" maxlength="80"/>

<label for="txtCriaSenhaUsuario"><?php echo $this->translate('senha')?>*</label>
<input name="txtCriaSenhaUsuario" type="password" class="single" id="txtCriaSenhaUsuario" value="<?php echo $this->novoUsuario['senha']?>" maxlength="10"/>

<label for="txtCriaRepeteSenha"><?php echo $this->translate('repeticao_senha')?>*</label>
<input name="txtCriaRepeteSenha" type="password" class="single" id="txtCriaRepeteSenha" value="<?php echo $this->novoUsuario['senha_repetida']?>" maxlength="10"/>

<?php
    if (isset($valoresPapel)) {
?>

<label><?php echo $this->translate('papel')?>*</label>
<select name="slcPapel" id="slcPapel">
<?php
        while (list($chave, $valor) = each($valoresPapel)) {
                $this->html->insertOption($chave, $valor, 1, $this->novoUsuario['papel']);
        }
?>
</select>

<?php
    }
?>

<div class="margin_1">
<input type="hidden" name="etapaEnvio" value="1"/>
<input type="hidden" name="codigoUsuario" value="<?php echo $this->novoUsuario['id']?>"/>
<input name="submit" id="submit" type="submit" value="<?php echo $this->translate('enviar')?>" alt="<?php echo $this->translate('enviar')?>" title="<?php echo $this->translate('enviar')?>" class="button_2" />
</div>

</form>

<?php
}
?>