<div id="breadcrumb"><?php echo $this->breadcrumb?></div>

<h1><?php echo $this->tituloPagina?></h1>

<?php
if ($this->usuarioPagina['senhaCadastrada']) {

    if (!$this->usuarioPagina['erroNoCadastroDaSenha']) {
?>

<!-- success -->
<p class="text_success">Sua senha foi alterada com sucesso. <a class="default_13" href="/autenticacao/login/acessa">Entre no sistema com sua nova senha.</a></p>
<!-- /success -->

<?php
    } else {
?>

<!-- result -->
<p class="text_error"><?php echo $this->translate('erro')?> Houve um erro no cadastro da sua senha.</p>
<!-- /result -->

<?php
    }
}



if ((!$this->usuarioPagina['erroComAsCredenciais']) && ((!$this->usuarioPagina['senhaCadastrada']) || (($this->usuarioPagina['senhaCadastrada']) && ($this->usuarioPagina['senhaCadastradaComErro'])))) {
    ?>

<form method="post" name="frmUsuario" action="<?php echo $_SERVER["REQUEST_URI"]?>" enctype="multipart/form-data" accept-charset="utf-8">

<p>* <?php echo $this->translate('campos_obrigatorios')?></p><br /><br />

<label for="txtRenovaSenhaUsuario"><?php echo $this->translate('senha')?>*</label>
<input name="txtRenovaSenhaUsuario" type="password" class="single" id="txtRenovaSenhaUsuario" value="<?php echo $this->usuarioPagina['senha']?>" maxlength="10"/>

<label for="txtRenovaRepeteSenha"><?php echo $this->translate('repeticao_senha')?>*</label>
<input name="txtRenovaRepeteSenha" type="password" class="single" id="txtRenovaRepeteSenha" value="<?php echo $this->usuarioPagina['senha_repetida']?>" maxlength="10"/>

<div class="margin_1">
<input type="hidden" name="etapaEnvio" value="1"/>
<input name="submit" id="submit" type="submit" value="<?php echo $this->translate('enviar')?>" alt="<?php echo $this->translate('enviar')?>" title="<?php echo $this->translate('enviar')?>" class="button_2" />
</div>

</form>

<?php
} else if (!$this->usuarioPagina['senhaCadastrada']) {
?>
<!-- result -->
<p class="text_error"><?php echo $this->translate('erro')?> <?php echo $this->usuarioPagina['mensagem_erro_senha']?>.</p>
<!-- /result -->


<?php } ?>
