<div id="breadcrumb"><?php echo $this->breadcrumb?></div>

<h1><?php echo $this->tituloPagina?></h1>

<?php
if ($this->solicitaSenha['mensagemEnviada']) {

    if (!$this->solicitaSenha['erroNaSolicitacaoDeSenha']) {
?>

<!-- success -->
<p class="text_success"><?php echo $this->translate($this->solicitaSenha['sucesso_envio_mensagem'])?></p>
<!-- /success -->

<?php
    } else {
?>

<!-- result -->
<p class="text_error"><?php echo $this->translate('erro')?> <?php echo $this->solicitaSenha['mensagem_erro_senha']?></p>
<!-- /result -->

<?php
    }
}

if ((!$this->solicitaSenha['mensagemEnviada']) || (($this->solicitaSenha['mensagemEnviada']) && ($this->solicitaSenha['erroNaSolicitacaoDeSenha']))) {
?>

<form method="post" name="frmUsuario" action="<?php echo $_SERVER["REQUEST_URI"]?>" enctype="multipart/form-data" accept-charset="utf-8">

<p>* <?php echo $this->translate('campos_obrigatorios')?></p><br /><br />

<label for="txtEmail"><?php echo $this->translate('email')?>*</label>
<input name="txtEmail" type="text" class="single" id="txtEmail" value="<?php echo $this->solicitaSenha['email']?>" maxlength="80"/>

<div class="margin_1">
<input type="hidden" name="etapaEnvio" value="1"/>
<input name="submit" id="submit" type="submit" value="<?php echo $this->translate('enviar')?>" alt="<?php echo $this->translate('enviar')?>" title="<?php echo $this->translate('enviar')?>" class="button_2" />
</div>

</form>

<?php
}
?>