        <script type="text/javascript">

        $(document).ready(function(){
            populateEditorField();
        });

        function populateEditorField() {
            $.getJSON('/admin/index/populate-editors', function(data) {
            var html = '';
            var len = data.length;
            html += '<option value="0">(##choose an editor)</option>';
            for (var i = 0; i< len; i++) {
                html += '<option value="' + data[i].id + '">' + data[i].name + '</option>';
            }
            $('#editor').empty();
            $('#editor').append(html);
            $('#editor').val($("#hidEditor").val())
            });
        }

</script>
<form id="sucessNewEditorForm">
        <input type="hidden" id="hidEditor" name="newEditorId" value="<?php echo $this->id ?>">
</form>
