          <script type="text/javascript">
            function populateEditorField() {

              $.getJSON('/works/helper/populate-editors', function(data) {
                var html = '';
                var len = data.length;
                html += '<option value="0">(##choose an editor)</option>';
                for (var i = 0; i< len; i++) {
                  html += '<option value="' + data[i].id + '">' + data[i].name + '</option>';
                }
                $('#editor').empty();
                $('#editor').append(html);
              });
            }
          </script>
          <div id="MainHeader">
            <h1><?php print($this->translate('#Create edition')) ?></h1>
          </div>
<?php echo $this->form; ?>
