          <script type="text/javascript">
            $(document).ready(function(){

                $('#hideNewEditorClick').click(function(){
                    $("#newEditorDiv").slideToggle();
                });

            });

          </script>
<?php echo $this->form; ?>
<p style="margin-top:-12px; margin-bottom: 12px; margin-left: 32px;"><a href="#newEditionForm" id="hideNewEditorClick"><?php echo $this->translate("#(hide)") ?></a></p>
