<div id="conteudo">

<h1><img src="/img/icone_biografia.png" align="absmiddle" alt="Exposição Virtual" /> Exposição Virtual</h1>


<h3>Mil Histórias</h3>
<p>04.10.2013 | <a href='/curiosidades-em/exposicao-virtual' title='Exposição Virtual'><strong>Exposição Virtual</strong></a><!-- | <a href="" title=""><img src="/img/icone_comentario.png" align="absmiddle" /> <strong>Comente</strong></a>--></p>
<div id="explore"><p><div class="img_legenda undefined" style="float: right; width: 240px;"><img title="Lançamento do livro " src="/img/up/05_01.jpg" alt="Lançamento do livro " width="200px"><p class="legenda">Lançamento do livro </p></div>Em seguida, o que houve foi uma verdadeira surpresa para mim: comecei a ganhar pr&ecirc;mios, de melhor livro nacional do ano, de melhor livro do bi&ecirc;nio, e muitos outros. At&eacute; mesmo do exterior veio o reconhecimento, com o Pr&ecirc;mio Casa de las Am&eacute;ricas, em Cuba, ao qual concorri num gesto de ousadia, com um livro infantil ("De Olho nas Penas") competindo com literatura adulta, e venci. Foi muito emocionante perceber que aquilo que eu gostava tanto de fazer chegava a outras pessoas.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p><div class="img_legenda undefined" style="float: left; width: 280px;"><img title="Eu e minha filha Luísa." src="/img/up/05_02.jpg" alt="Eu e minha filha Luísa." width="240px"><p class="legenda">Eu e minha filha Luísa.</p></div>Em 1983, nasceu Lu&iacute;sa. No mesmo ano, tomei coragem e publiquei meu primeiro romance para adultos, "Alice e Ulisses", muito bem recebido pela cr&iacute;tica. Ao mesmo tempo, meus livros foram come&ccedil;ando a ser traduzidos no exterior, primeiro nos pa&iacute;ses escandinavos e, em seguida, na Alemanha, na Fran&ccedil;a e na Espanha. Paralelamente, fui passando a fazer palestras para professores pelo interior do Brasil e desenvolvi cursos e semin&aacute;rios sobre promo&ccedil;&atilde;o de leitura no exterior.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p><div class="img_legenda undefined" style="float: right; width: 280px;"><img title="Feliz com a tranqüilidade de Manguinhos." src="/img/up/05_03.jpg" alt="Feliz com a tranqüilidade de Manguinhos." width="240px"><p class="legenda">Feliz com a tranqüilidade de Manguinhos.</p></div>De 1986 a 1988, fizemos uma coisa maravilhosa: deixamos a cidade grande e nos mudamos para uma casinha pequenina em Manguinhos. Uma verdadeira volta as ra&iacute;zes. Uma vida muito modesta e recolhida, em contato direto com o mar e a natureza. Lu&iacute;sa ia a escola com os filhos dos moradores locais, Louren&ccedil;o compunha e tocava, eu escrevia.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p><div class="img_legenda undefined" style="float: left; width: 280px;"><img title="Passeando no Regent´s Park, Londres - 1990." src="/img/up/05_04.jpg" alt="Passeando no Regent´s Park, Londres - 1990." width="240px"><p class="legenda">Passeando no Regent´s Park, Londres - 1990.</p></div>De Manguinhos para o mundo... Em fim de 1989, me ofereceram um novo contrato com a BBC e voltei para Londres, onde passei oito meses e terminei de escrever o romance "Canteiros de Saturno". Pouco depois de voltar ao Brasil, em meio a muito trabalho, tive problemas de sa&uacute;de muito s&eacute;rios. Por um longo tempo toda minha vida ficou direcionada a enfrentar essa situa&ccedil;&atilde;o, ajudada pelo carinho de tanta gente que me quer bem e apoiada pelo meu trabalho.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p><div class="img_legenda undefined" style="float: right; width: 240px;"><img title="Junto da estátua de Hans Christian Andersen, em Nova Iorque." src="/img/up/05_05.jpg" alt="Junto da estátua de Hans Christian Andersen, em Nova Iorque." width="200px"><p class="legenda">Junto da estátua de Hans Christian Andersen, em Nova Iorque.</p></div>Os &uacute;ltimos anos tem sido principalmente de coisas boas, que as outras a gente esquece. Dois netos maravilhosos: Henrique em 1996 e Isadora em 2000. Nesse mesmo ano, ganhei tamb&eacute;m o pr&ecirc;mio Hans Christian Andersen, coisa que me trouxe muita alegria. &Eacute; incr&iacute;vel saber que um j&uacute;ri internacional, sem nenhum brasileiro, analisou o conjunto de minha obra e concluiu que eu merecia ser considerada a melhor autora do mundo...</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p><div class="img_legenda undefined" style="float: left; width: 320px;"><img title="Com o presidente Fernando Henrique Cardoso, recebendo a Ordem do Mérito Cultural." src="/img/up/05_06.jpg" alt="Com o presidente Fernando Henrique Cardoso, recebendo a Ordem do Mérito Cultural." width="280px"><p class="legenda">Com o presidente Fernando Henrique Cardoso, recebendo a Ordem do Mérito Cultural.</p></div>Em 2001, tive uma surpresa maravilhosa: ganhei o maior pr&ecirc;mio liter&aacute;rio nacional, o Machado de Assis, que a Academia Brasileira de Letras confere por toda a obra de um autor. Uma honra dessas ainda veio se somar as condecora&ccedil;&otilde;es. Recebi a Medalha Tiradentes, da Assembl&eacute;ia Legislativa do Rio, e a Ordem do M&eacute;rito Cultural, da Presid&ecirc;ncia da Rep&uacute;blica. Uma verdadeira consagra&ccedil;&atilde;o. Puxa, nem com uma varinha m&aacute;gica uma fada-madrinha podia me dar isso...&nbsp;
</p></div>
<p style="float: left"><a href="/expo/agora-para-ficar">Anterior</a></p><p style="float: right"><a href="/expo/tempo-de-colheita">Continuar</a></p>

</div>
