<?php
$pageData = $this->pageData;
?>
<!-- conteudo -->
<div id="conteudo">

<h1><img src="/img/icone_livros.png" align="absmiddle" alt="<?php echo $this->translate("#Stories") ?>" /><?php echo $this->translate("#Stories") ?></h1>

<!-- destaques -->
<div class="clearfix">

<div class="float_left livro_destaque">
<a href="<?php echo $pageData['leftSpecialUri']?>"><img src="<?php echo $pageData['leftSpecialImageUri']?>" /></a>
<h3><a href="<?php echo $pageData['leftSpecialUri']?>"><?php echo $pageData['leftSpecialTitle']?></a></h3>
<p><?php echo $pageData['leftSpecialSummary']?> <a href="<?php echo $pageData['leftSpecialUri']?>" class="mais"> mais</a></p>
</div>

<div class="float_right livro_destaque">
<a href="<?php echo $pageData['rightSpecialUri']?>"><img src="<?php echo $pageData['rightSpecialImageUri']?>" /></a>
<h3><a href="<?php echo $pageData['rightSpecialUri']?>"><?php echo $pageData['rightSpecialTitle']?></a></h3>
<p><?php echo $pageData['rightSpecialSummary']?><a href="<?php echo $pageData['rightSpecialUri']?>" class="mais"> mais</a></p>
</div>

</div>
<!-- /destaques -->

<!-- categorias -->
<div id="livros_categorias" class="clearfix">
<h2><?php echo $this->translate("#Stories by category") ?></h2>
<a href="/historias/infantis"><?php echo $this->translate("#Children") ?></a><a href="/ficção"><?php echo $this->translate("#Fiction") ?></a><a href=""><?php echo $this->translate("#Young people") ?></a><a href="/ensaios"><?php echo $this->translate("#Essays") ?></a>
</div>
<!-- categorias -->



</div>
<!-- /conteudo -->
