<?php
  $controller = Zend_Controller_Front::getInstance();
  $request = $controller->getRequest();
  $controller->setParam('outerModule', $request->getModuleName());
  $params = $controller->getParams();
?>
<script type="text/javascript" src="/js/jquery.pajinate.js"></script>

<!-- container -->
<div id="livros" class="clearfix">

<!-- header -->
<?php echo $this->action('header', 'include', 'includes') ?>
<!-- /header -->

<!-- breadcrumb -->
<div id="breadcrumb">
<?php echo $this->navigation()->breadcrumbs()->setLinkLast(false)->setMinDepth(0)->setSeparator(" &rsaquo; "); ?>
</div>
<!-- /breadcrumb -->
<?php echo $this->layout()->content; ?>

<!-- lateral -->
<div id="lateral">
<?php echo $this->action('categories', 'include', 'includes') ?>
<?php echo $this->action('search', 'include', 'includes') ?>
</div>
<!-- /lateral -->

<!-- rodape -->
<?php echo $this->action('footer', 'include', 'includes') ?>
<!-- /rodape -->

</div>
<!-- /container -->
