<?php
  $controller = Zend_Controller_Front::getInstance();
  $request = $controller->getRequest();
  $controller->setParam('outerModule', $request->getModuleName());
  $params = $controller->getParams();
?>

<!-- container -->
<div id="home" class="clearfix">

<!-- header -->
<?php echo $this->action('header', 'include', 'includes') ?>
<!-- /header -->

<!-- conteudo -->
<?php echo $this->layout()->content; ?>
<!-- /conteudo -->

<!-- rodape -->
<?php echo $this->action('footer-home', 'include', 'includes') ?>
<!-- /rodape -->

</div>
<!-- /container -->
