<div id="header_login">
	<div id="header_wrapper_3" class="clearfix">
		<a href="/"><img src="/img/blank.gif" width="255" height="65" alt="Ao Cubo" title="Ao Cubo" border="0" class="float_left margin_20" /></a>
            <img src="/img/blank.gif" width="180" height="38" alt="AMM" title="AMM" border="0" class="float_left margin_19" />
	</div>
</div>

<!-- structure -->
<div id="structure_login" class="clearfix">

<?php echo $this->layout()->content ?>

</div>
<!-- /structure -->