<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<?php include ("meta.phtml") ?>

<link rel="stylesheet" href="/css/styles.css" type="text/css" media="screen"/>
<link rel="stylesheet" href="/css/css3.css" type="text/css" media="screen"/>
<link rel="stylesheet" href="/css/forms.css" type="text/css" media="screen" />

<title><?php echo $this->layout()->title?></title>

</head>

<body>

<!-- header -->
<?php echo $this->action('inclui', 'header', 'includes') ?>
<!-- /header -->

<!-- structure -->
<div id="structure" class="clearfix">

<!-- content -->
<div id="main_content">
<?php echo $this->layout()->content ?>
</div>
<!-- /content -->

<!-- apendix -->
<div id="apendix">&nbsp;</div>
<!-- /apendix -->

</div>
<!-- /structure -->

<!-- footer -->
<?php /*include ("footer.phtml")*/ ?>
<!-- /footer -->

</body>
</html>