    <meta http-equiv="content-language" content="pt-br" />
    <meta http-equiv="Cache-Control" content="no-cache" />
    <meta http-equiv="Pragma" content="no-cache" />
    <meta name="googlebot" content="noarchive" />
    <meta name="robots" content="index,follow" />
    <meta name="googlebot" content="ALL" />
    <?php echo $this->headMeta()->appendName('keywords', $this->keywords); ?>
    <meta name="description" content="..." />
    <meta name="google" content="notranslate" />

    <meta charset="utf-8">
