<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<?php echo $this->headTitle() ?>
<?php include ("meta.phtml") ?>

<script type="text/javascript" src="/js/jquery-1.5.min.js"></script>

<script type="text/javascript" src="/js/jquery.pajinate.js"></script>

<script type="text/javascript" src="/js/easytabs.js"></script>
<script type="text/javascript" language="javascript" src="/js/jquery.dataTables.js"></script>
<script type="text/javascript" src="/js/tinymce/tinymce.min.js"></script>
<script type="text/javascript">
tinymce.init({
    selector: "textarea#richtext",
    theme: "modern",
    relative_urls: false,
    width: 600,
    height: 200,
    plugins: [
         "advlist link image jbimages lists charmap preview hr anchor pagebreak spellchecker",
         "searchreplace wordcount code",
         "emoticons paste textcolor"
   ],
   content_css: "css/content.css",
   toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | print preview media fullpage | forecolor backcolor emoticons | jbimages",
   style_formats: [
        {title: 'Bold text', inline: 'b'},
        {title: 'Red text', inline: 'span', styles: {color: '#ff0000'}},
        {title: 'Red header', block: 'h1', styles: {color: '#ff0000'}},
        {title: 'Example 1', inline: 'span', classes: 'example1'},
        {title: 'Example 2', inline: 'span', classes: 'example2'},
        {title: 'Table styles'},
        {title: 'Table row 1', selector: 'tr', classes: 'tablerow1'}
    ]
 });
</script>
<link rel="stylesheet" href="/css/estilo.css" type="text/css" media="screen" />


</head>
  <body>
    <div class="container" id="Envelope">
<?php
  if ($this->layout()->nestedLayout) {
      $this->layout()->setLayout($this->layout()->nestedLayout);
  } else {
      $this->layout()->setLayout('inner');
  }
  echo $this->layout()->render();
?>
<!-- footer -->
<?php //echo $this->action('inclui', 'footer', 'includes') ?>
<!-- /footer -->
    </div><!-- #Envelope -->
  </body>
</html>
