<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<?php echo $this->headTitle() ?>
<?php include ("meta.phtml") ?>

<script type="text/javascript" src="/js/jquery-1.5.min.js"></script>


<script type="text/javascript" src="/js/easytabs.js"></script>
<link rel="stylesheet" href="/css/estilo.css" type="text/css" media="screen" />


</head>
  <body>
    <div class="container" id="Envelope">
<?php
  if ($this->layout()->nestedLayout) {
      $this->layout()->setLayout($this->layout()->nestedLayout);
  } else {
      $this->layout()->setLayout('inner');
  }
  echo $this->layout()->render();
?>
<!-- footer -->
<?php //echo $this->action('inclui', 'footer', 'includes') ?>
<!-- /footer -->
    </div><!-- #Envelope -->
  </body>
</html>
<?php
$env = APPLICATION_ENV;
if ($env = 'production') include ("analyticstracking.phtml");
?>
